### ISSUE TITLE
Implement TrustedFederatedExecutor over insecure channels

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/rfcs#21]
This federated executor uses a distinct trusted third-party executor without formal placement and typically referenced through `RemoteExecutor`. To compute an aggregation it collections values from the clients, sends them to the third-party executor, instructs it to aggregate them, and finally pulls back the result. Unrelated instructions are forwarded to the executor in the server stack as usual.

This issue does not deal with encryption values in transit but simply builds the skeleton for dealing with this in a follow-up issue.

The built-in `FederatedExecutor` can likely provide some guidance towards moving values around.

**Comment by jvmncs** [comment]
>Unrelated instructions are forwarded to the executor in the server stack as usual.

It's my impression that unrelated instructions are generally forwarded to the unplaced executor stack. Is this not the case?
